---
- name: Build Base Servers For Kubernetes Install
  hosts: servers
  become: yes
  tasks:
  - name: Ensure Servers Are Up To Date
    ansible.builtin.apt:
      name: "*"
      state: latest
  - name: Disable Swap
    ansible.builtin.command: swapoff -a
  - name: Ensure Swap Is Not Enabled On Reboot
    ansible.builtin.command: 
      cmd: sudo sed -i '/swap/ s/^#*/# /' /etc/fstab
  - name: Ensure containerd.conf File Exists
    file:
      path: /etc/modules-load.d/containerd.conf
      state: touch
  - name: Set Kernel Modules Required for containerd.conf
    ansible.builtin.blockinfile:
      path: /etc/modules-load.d/containerd.conf
      block: |
        overlay 
        br_netfilter 
  - name: Load Kernel Modules
    ansible.builtin.command: 
      cmd: modprobe overlay
  - name: Load Kernel Modules
    ansible.builtin.command: 
      cmd: modprobe br_netfilter
  - name: Ensure kubernetes.conf File Exists
    file:
      path: /etc/sysctl.d/kubernetes.conf
      state: touch
  - name: Set Kernel Parameteres
    ansible.builtin.blockinfile:
      path: /etc/sysctl.d/kubernetes.conf
      block: |
        net.bridge.bridge-nf-call-ip6tables=1
        net.bridge.bridge-nf-call-iptables=1
        net.ipv4.ip_forward=1
  - name: Reload Changes To Kernel
    ansible.builtin.shell:
      cmd: "sysctl --system"
  - name: Install Containerd Depdencies
    ansible.builtin.apt:
      pkg:
      - curl
      - wget
      - gnupg2
      - software-properties-common 
      - apt-transport-https 
      - ca-certificates
  - name: Enable Docker Repository - Get Apt Key
    ansible.builtin.command: 
      cmd: wget https://download.docker.com/linux/ubuntu/gpg 
  - name: Enable Docker Repository - Add Apt Key
    ansible.builtin.command:
      cmd: apt-key add gpg
  - name: Enable Docker Repository - Add Repository
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
      state: present
  - name: Update Repositories Cache and Install "containerd.io" package
    ansible.builtin.apt:
      name: containerd.io
      update_cache: yes
  - name: Get Containerd Config
    ansible.builtin.shell: 
      cmd: containerd config default | tee /etc/containerd/config.toml
  - name: Configure containerd so that it starts using systemd as cgroup.
    ansible.builtin.command: 
      cmd: sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
  - name: Restart and Enable Containerd
    ansible.builtin.systemd:
      name: containerd.service
      state: restarted
      enabled: yes
  - name: Get Kubernetes Apt Key
    ansible.builtin.command: 
      cmd: wget https://packages.cloud.google.com/apt/doc/apt-key.gpg 
  - name: Add Kubernetes Apt Key
    ansible.builtin.command:
      cmd: apt-key add apt-key.gpg
  - name: Add Repository for Kubernetes
    ansible.builtin.apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
  - name: Update repositories cache and install kubelet, kubeadm and kubectl
    ansible.builtin.apt:
      pkg:
        - kubelet
        - kubeadm
        - kubectl
      update_cache: yes
  - name: Pin Versions of Kubernetes Unless We Say to Update
    ansible.builtin.command: 
      cmd: apt-mark hold kubelet kubeadm kubectl
