---
- name: Tune Firewall for Master Nodes
  hosts: masters
  become: yes
  tasks:
  - name: Ensure SSH Allowed
    community.general.ufw:
      rule: allow
      name: OpenSSH

  - name: Deny everything
    community.general.ufw:
      state: enabled
      default: deny

  - name: Open Required Ports
    community.general.ufw:
      rule: allow
      port: "{{item.port}}"
      proto: "{{item.proto}}"
    with_items:
      - {port: "6443", proto: "tcp" }
      - {port: "2379:2380", proto: "tcp" }
      - {port: "10250", proto: "tcp" }
      - {port: "10259", proto: "tcp"}
      - {port: "10257", proto: "tcp" }
      - {port: "8472", proto: "udp" }
      - {port: "8285", proto: "udp" }
      - {port: "7946", proto: "udp" }
      - {port: "7946", proto: "tcp" }

  - name: Ensure UFW Service Enabled
    ansible.builtin.systemd:
      name: ufw.service
      state: started
      enabled: yes

- name: Tune Firewall for Worker Nodes
  hosts: workers
  become: yes
  tasks:
  - name: Ensure SSH Allowed
    community.general.ufw:
      rule: allow
      name: OpenSSH

  - name: Deny everything
    community.general.ufw:
      state: enabled
      default: deny

  - name: Open Required Ports
    community.general.ufw:
      rule: allow
      port: "{{item.port}}"
      proto: "{{item.proto}}"
    with_items:
      - {port: "30000:32767", proto: "tcp" }
      - {port: "10250", proto: "tcp" }
      - {port: "8285", proto: "udp" }
      - {port: "8472", proto: "udp" }
      - {port: "7946", proto: "udp" }
      - {port: "7946", proto: "tcp" }

  - name: Ensure UFW Service Enabled
    ansible.builtin.systemd:
      name: ufw.service
      state: started
      enabled: yes